/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leonardovechieti.dev.project.views;

import com.leonardovechieti.dev.project.model.Usuario;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Leonardo
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public Usuario usuario;
    
    public PrincipalView() {
        initComponents();
        //Seta os dados do usuario logado

        //Formata menu
        //menuBarraPrincipal.setBackground(Color.decode("#2E2E2E"));
        //menuBarraPrincipal.setForeground(Color.decode("#FFFFFF"));
//        menuBarraPrincipal.setBorderPainted(false);
//        menuBarraPrincipal.setFocusable(false);
//        menuBarraPrincipal.setOpaque(true);
//        menuBarraPrincipal.setRequestFocusEnabled(false);
//        //menuBarraPrincipal.setRolloverEnabled(false);
//        menuBarraPrincipal.setVerifyInputWhenFocusTarget(false);
//        menuBarraPrincipal.setVisible(true);
//        menuBarraPrincipal.setBorder(null);

        //Seta uma margem para o menu
        menuBarraPrincipal.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));





    }
    public PrincipalView(Usuario usuario) {
        initComponents();
        //Seta icon da janela
        setIcon();
        //Seta os dados do usuario logado
        setUsuario(usuario);
        this.setVisible(true);
    }
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/leonardovechieti/dev/project/icon/iconesistema.png")));
    }
    
    public void setUsuario(Usuario usuario){
        this.usuario = usuario;
        if(usuario != null){
            labelNomeUsuario.setText(usuario.getNome());
            labelIdUsuario.setText(String.valueOf(usuario.getId()));
            //Seta data atual formatada
            labelDateTime.setText(new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date(System.currentTimeMillis())));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        barraCadastrarProdutos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        barraListarProdutos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        barraNovoLancamento = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        labelVersao = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        labelIdEmpresa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNomeEmpresa = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        labelIdUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNomeUsuario = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        lblData1 = new javax.swing.JLabel();
        labelDateTime = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        menuBarraPrincipal = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuCadastrarProdutos = new javax.swing.JMenuItem();
        menuListarProdutos = new javax.swing.JMenuItem();
        menuCadastrarCentroDeCusto = new javax.swing.JMenuItem();
        menuCadastrarOpercaoes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadastrarProdutos2 = new javax.swing.JMenuItem();
        menuListarLancamento = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        menuCadastrarUsuarios = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dev - Software");

        jToolBar1.setRollover(true);

        barraCadastrarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/produto1.png"))); // NOI18N
        barraCadastrarProdutos.setToolTipText("");
        barraCadastrarProdutos.setFocusable(false);
        barraCadastrarProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barraCadastrarProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraCadastrarProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(barraCadastrarProdutos);
        jToolBar1.add(jSeparator2);

        barraListarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/produtoList1.png"))); // NOI18N
        barraListarProdutos.setFocusable(false);
        barraListarProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barraListarProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraListarProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(barraListarProdutos);
        jToolBar1.add(jSeparator1);

        barraNovoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/graficobarras.png"))); // NOI18N
        barraNovoLancamento.setFocusable(false);
        barraNovoLancamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barraNovoLancamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraNovoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraNovoLancamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(barraNovoLancamento);

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);
        jToolBar3.add(jSeparator9);

        labelVersao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelVersao.setText("Versão: 1.0");
        jToolBar3.add(labelVersao);
        jToolBar3.add(jSeparator10);

        labelIdEmpresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdEmpresa.setText("ID");
        jToolBar3.add(labelIdEmpresa);

        jLabel3.setText(" - ");
        jToolBar3.add(jLabel3);

        labelNomeEmpresa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNomeEmpresa.setText("Nome da Empresa");
        jToolBar3.add(labelNomeEmpresa);
        jToolBar3.add(jSeparator11);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Usuário: ");
        jToolBar3.add(jLabel2);

        labelIdUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdUsuario.setText("ID");
        jToolBar3.add(labelIdUsuario);

        jLabel4.setText(" - ");
        jToolBar3.add(jLabel4);

        labelNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNomeUsuario.setText("Nome do Usuário");
        jToolBar3.add(labelNomeUsuario);
        jToolBar3.add(jSeparator12);

        lblData1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblData1.setText("Data Atual:  ");
        jToolBar3.add(lblData1);

        labelDateTime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelDateTime.setText("Data");
        jToolBar3.add(labelDateTime);
        jToolBar3.add(jSeparator13);

        menuBarraPrincipal.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jMenu5.setText("Cadastros");
        jMenu5.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/produto1.png"))); // NOI18N
        jMenu6.setText("Produtos e serviços");
        jMenu6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        menuCadastrarProdutos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuCadastrarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/produto1.png"))); // NOI18N
        menuCadastrarProdutos.setText("Cadastrar");
        menuCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarProdutosActionPerformed(evt);
            }
        });
        jMenu6.add(menuCadastrarProdutos);

        menuListarProdutos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuListarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/produtoList1.png"))); // NOI18N
        menuListarProdutos.setText("Listar");
        menuListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarProdutosActionPerformed(evt);
            }
        });
        jMenu6.add(menuListarProdutos);

        jMenu5.add(jMenu6);

        menuCadastrarCentroDeCusto.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuCadastrarCentroDeCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/statistics.png"))); // NOI18N
        menuCadastrarCentroDeCusto.setText("Centro de Custo");
        menuCadastrarCentroDeCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarCentroDeCustoActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadastrarCentroDeCusto);

        menuCadastrarOpercaoes.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuCadastrarOpercaoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/integracao.png"))); // NOI18N
        menuCadastrarOpercaoes.setText("Operçoes");
        menuCadastrarOpercaoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarOpercaoesActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadastrarOpercaoes);

        menuBarraPrincipal.add(jMenu5);

        jMenu2.setText("Movimentações");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        menuCadastrarProdutos2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuCadastrarProdutos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/graficobarras.png"))); // NOI18N
        menuCadastrarProdutos2.setText("Novo Lançamento Financeiro");
        menuCadastrarProdutos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarProdutos2ActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastrarProdutos2);

        menuListarLancamento.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuListarLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/garficoelupa.png"))); // NOI18N
        menuListarLancamento.setText("Listar Lançamento Financeiro");
        menuListarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarLancamentoActionPerformed(evt);
            }
        });
        jMenu2.add(menuListarLancamento);

        menuBarraPrincipal.add(jMenu2);

        jMenu4.setText("Relatórios");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuBarraPrincipal.add(jMenu4);

        jMenu7.setText("Sistema");
        jMenu7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        menuCadastrarUsuarios.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuCadastrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leonardovechieti/dev/project/icon/pastapessoaamarela.png"))); // NOI18N
        menuCadastrarUsuarios.setText("Usuários");
        menuCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarUsuariosActionPerformed(evt);
            }
        });
        jMenu7.add(menuCadastrarUsuarios);

        menuBarraPrincipal.add(jMenu7);

        setJMenuBar(menuBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barraCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraCadastrarProdutosActionPerformed
        // TODO add your handling code here:
        CadastroProdutosView cadastro = new CadastroProdutosView();
        cadastro.setVisible(true);
    }//GEN-LAST:event_barraCadastrarProdutosActionPerformed

    private void menuCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarProdutosActionPerformed
        // TODO add your handling code here:
        CadastroProdutosView cadastro = new CadastroProdutosView();
        cadastro.setVisible(true);
    }//GEN-LAST:event_menuCadastrarProdutosActionPerformed

    private void menuListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarProdutosActionPerformed
        // TODO add your handling code here:
        ListProdutosView listar = new ListProdutosView();
        listar.setVisible(true);
    }//GEN-LAST:event_menuListarProdutosActionPerformed

    private void barraListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraListarProdutosActionPerformed
        // TODO add your handling code here:
        ListProdutosView listar = new ListProdutosView();
        listar.setVisible(true);
    }//GEN-LAST:event_barraListarProdutosActionPerformed

    private void menuCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarUsuariosActionPerformed
        // TODO add your handling code here:
        CadastroUsuariosView cadastro = new CadastroUsuariosView();
        cadastro.setVisible(true);
    }//GEN-LAST:event_menuCadastrarUsuariosActionPerformed

    private void menuCadastrarCentroDeCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarCentroDeCustoActionPerformed
        // TODO add your handling code here:
        CadastroCentroDeCusto centroDeCusto = new CadastroCentroDeCusto();
        centroDeCusto.setVisible(true);
    }//GEN-LAST:event_menuCadastrarCentroDeCustoActionPerformed

    private void menuCadastrarProdutos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarProdutos2ActionPerformed
        // TODO add your handling code here:
        NovoLancamentoView lancamento = new NovoLancamentoView();
        lancamento.setVisible(true);
    }//GEN-LAST:event_menuCadastrarProdutos2ActionPerformed

    private void menuCadastrarOpercaoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarOpercaoesActionPerformed
        // TODO add your handling code here:
        CadastroOperacoes opercao = new CadastroOperacoes();
        opercao.setVisible(true);
    }//GEN-LAST:event_menuCadastrarOpercaoesActionPerformed

    private void barraNovoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraNovoLancamentoActionPerformed
        NovoLancamentoView lancamento = new NovoLancamentoView();
        lancamento.setVisible(true);
    }//GEN-LAST:event_barraNovoLancamentoActionPerformed

    private void menuListarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListarLancamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barraCadastrarProdutos;
    private javax.swing.JButton barraListarProdutos;
    private javax.swing.JButton barraNovoLancamento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel labelDateTime;
    public static javax.swing.JLabel labelIdEmpresa;
    public static javax.swing.JLabel labelIdUsuario;
    public static javax.swing.JLabel labelNomeEmpresa;
    public static javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JLabel lblData1;
    private javax.swing.JMenuBar menuBarraPrincipal;
    private javax.swing.JMenuItem menuCadastrarCentroDeCusto;
    private javax.swing.JMenuItem menuCadastrarOpercaoes;
    private javax.swing.JMenuItem menuCadastrarProdutos;
    private javax.swing.JMenuItem menuCadastrarProdutos2;
    private javax.swing.JMenuItem menuCadastrarUsuarios;
    private javax.swing.JMenuItem menuListarLancamento;
    private javax.swing.JMenuItem menuListarProdutos;
    // End of variables declaration//GEN-END:variables
}
